// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Aside: typeof import('./src/components/Aside/Aside.vue')['default']
    BasicLayout: typeof import('./src/components/layouts/BasicLayout.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    Footer: typeof import('./src/components/Footer/Footer.vue')['default']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    HeaderView: typeof import('./src/components/layout/HeaderView.vue')['default']
    HybridLayout: typeof import('./src/components/layouts/HybridLayout.vue')['default']
    OffsetLayout: typeof import('./src/components/layouts/OffsetLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpaceLayout: typeof import('./src/components/layouts/SpaceLayout.vue')['default']
  }
}

export {}
