// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AsideView: typeof import('./src/components/layout/AsideView.vue')['default']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    HeaderView: typeof import('./src/components/layout/HeaderView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
